// <auto-generated />
using System;
using MACUTION.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MACUTION.Migrations
{
    [DbContext(typeof(MacutionDatabase))]
    [Migration("20260226102544_first1.1")]
    partial class first11
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MACUTION.Data.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Image_URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("MACUTION.Data.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Buy_Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("creation_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("product_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("user_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("user_id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("MACUTION.Data.Request_admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("give_access_person_id")
                        .HasColumnType("int");

                    b.Property<int>("request_person_id")
                        .HasColumnType("int");

                    b.Property<bool>("verified_admin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("give_access_person_id");

                    b.HasIndex("request_person_id")
                        .IsUnique();

                    b.ToTable("request_Admins");
                });

            modelBuilder.Entity("MACUTION.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MobileNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImageUrl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<DateTime>("createdAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<bool>("right_to_add")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("USER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Monvel",
                            Email = "harshid.hadiya@gmail.com",
                            MobileNumber = 2341,
                            Name = "hadiya harshid",
                            Password = "12345",
                            createdAt = new DateTime(2026, 2, 26, 14, 44, 45, 31, DateTimeKind.Local).AddTicks(8120),
                            right_to_add = true,
                            role = "ADMIN"
                        });
                });

            modelBuilder.Entity("MACUTION.Data.Verifier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isverified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("product_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("verificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("verifier_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("product_id")
                        .IsUnique();

                    b.HasIndex("verifier_id");

                    b.ToTable("verifiers");
                });

            modelBuilder.Entity("MACUTION.Data.Image", b =>
                {
                    b.HasOne("MACUTION.Data.Product", "product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");
                });

            modelBuilder.Entity("MACUTION.Data.Product", b =>
                {
                    b.HasOne("MACUTION.Data.User", "user")
                        .WithMany("products")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("user");
                });

            modelBuilder.Entity("MACUTION.Data.Request_admin", b =>
                {
                    b.HasOne("MACUTION.Data.User", "permission_person")
                        .WithMany("given_access")
                        .HasForeignKey("give_access_person_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MACUTION.Data.User", "requet_person")
                        .WithOne("request")
                        .HasForeignKey("MACUTION.Data.Request_admin", "request_person_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("permission_person");

                    b.Navigation("requet_person");
                });

            modelBuilder.Entity("MACUTION.Data.Verifier", b =>
                {
                    b.HasOne("MACUTION.Data.Product", "product")
                        .WithOne("verifier")
                        .HasForeignKey("MACUTION.Data.Verifier", "product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MACUTION.Data.User", "user")
                        .WithMany("verifiers")
                        .HasForeignKey("verifier_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");

                    b.Navigation("user");
                });

            modelBuilder.Entity("MACUTION.Data.Product", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("verifier");
                });

            modelBuilder.Entity("MACUTION.Data.User", b =>
                {
                    b.Navigation("given_access");

                    b.Navigation("products");

                    b.Navigation("request");

                    b.Navigation("verifiers");
                });
#pragma warning restore 612, 618
        }
    }
}
